# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Skyline DataMiner Deploy Action
        # You may pin to the exact commit or the version.
        # uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@5d9d2739772b3d52b9848ce738c5e04f36b6444f
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.29
        with:
              api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
              solution-path: EmpowerHelloWorld.sln
              artifact-name: EmpowerHelloWorld
              version: 1.0.1
              build-number: ${{ github.run_number }}
